create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, business_name text not null default 'WiFi Saya', owner_name text, whatsapp_country_code text not null default '62', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.internet_packages (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, speed text, monthly_price numeric(12,2) not null default 0 check (monthly_price >= 0), description text, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, package_id uuid references public.internet_packages(id) on delete set null, full_name text not null, phone text not null default '', address text not null default '', monthly_price numeric(12,2) not null default 0 check (monthly_price >= 0), due_day smallint not null default 1 check (due_day between 1 and 31), status text not null default 'active' check (status in ('active','isolated','inactive')), started_at date not null default current_date, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.invoices (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, customer_id uuid not null references public.customers(id) on delete cascade, period date not null, amount numeric(12,2) not null check (amount >= 0), due_date date not null, status text not null default 'unpaid' check (status in ('unpaid','partial','paid')), note text, created_at timestamptz not null default now(), unique (user_id, customer_id, period));
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, invoice_id uuid references public.invoices(id) on delete set null, customer_id uuid not null references public.customers(id) on delete cascade, amount numeric(12,2) not null check (amount > 0), method text not null default 'cash', paid_at timestamptz not null default now(), note text, created_at timestamptz not null default now());
create table if not exists public.message_templates (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, message text not null, category text not null default 'tagihan', created_at timestamptz not null default now());
create index if not exists customers_user_status_idx on public.customers(user_id, status);
create index if not exists invoices_user_due_idx on public.invoices(user_id, due_date, status);
create index if not exists payments_user_paid_idx on public.payments(user_id, paid_at desc);
create index if not exists customers_user_phone_idx on public.customers(user_id, phone);
alter table public.profiles enable row level security;
alter table public.internet_packages enable row level security;
alter table public.customers enable row level security;
alter table public.invoices enable row level security;
alter table public.payments enable row level security;
alter table public.message_templates enable row level security;
create policy "profiles are private to owner" on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());
create policy "packages are private to owner" on public.internet_packages for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "customers are private to owner" on public.customers for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "invoices are private to owner" on public.invoices for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "payments are private to owner" on public.payments for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "templates are private to owner" on public.message_templates for all using (user_id = auth.uid()) with check (user_id = auth.uid());
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles, public.internet_packages, public.customers, public.invoices, public.payments, public.message_templates to authenticated;
